name: Detect Changes

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  detect-changes:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print information
        run: |
          echo ${{ github.event_name }}
          echo $(date +'%Y-%m-%d %H:%M:%S')
          echo ${GITHUB_REF#refs/heads/}
          echo ${GITHUB_ACTOR}"
          echo ${GITHUB_SHA}
          echo $(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | wc -l)
